HOST: http://www.silex.me/api/v1.0/

--- Unifile API ---
---
Welcome to the our sample API documentation. All comments can be written in (support [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax)
---

--
Services utilities
Utilities to discover services
--
List services
GET /services/list
< 200
< Content-Type: application/json
[
  {
    "name": "dropbox",
    "display_name": "Dropbox",
    "image_small": "unifile-assets/services/dropbox.png",
    "description": "Edit html files from your Dropbox.",
    "visible": true,
    "isLoggedIn": true,
    "isConnected": true,
    "isOAuth": true,
    "user": {
      "display_name": "Alex Hoyau",
      "quota_info": {
        "available": 5234491392,
        "used": 2899550907
      }
    }
  },
  {
    "name": "ftp",
    "display_name": "FTP",
    "image_small": "unifile-assets/services/ftp.png",
    "description": "Edit files on a web server.",
    "visible": true,
    "isLoggedIn": false,
    "isConnected": false,
    "isOAuth": false
  }
]
